stages:
  - deploy
deploy:
  stage: deploy
  environment: admin
  script:
    - echo "deploy ing...";
    - curl "http://webhook.vrcdkj.cn/deploy.php?branch=master&env=fadmin&access_token=none"
    - curl "http://webhook.vrcdkj.cn/deploy.php?branch=master&env=staging_admin&access_token=none"
  only:
    - master